project:
  type: website
  output-dir: _site
  resources: 
    - /data

website:
  title: "水産海洋データ解析演習I・II"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: Home
        href: index.qmd
      - text: サイトについて 
        href: about.qmd
      - section: "基礎"
        contents:
          - kiso/01-assignment.qmd
          - kiso/02-fundamentals.qmd
          - kiso/03-objects.qmd
          - kiso/04-vector.qmd
          - kiso/05-functions.qmd
      - section: "tidyverse"
        contents:
          - tidyverse/01-about.qmd
          - tidyverse/10-dplyr.qmd
          - tidyverse/20-dplyr.qmd
          - tidyverse/30-readr.qmd
      - section: "作図 (ggplot2)"
        contents:
          - ggplot2/01-about.qmd
          - ggplot2/10-points.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
  


